name: Example workflow for S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn install

        - name: Build
          run: yarn build

        - name: Deploy S3
          # S3にデプロイする権限のあるIAM
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: aws s3 cp --recursive --region ap-northeast-1 dist/ s3://online-code
          # CloudFrontのキャッシュを削除する
          