name: Example workflow for S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn install

        - name: Build
          run: yarn build

          # S3にデプロイ
        - name: Upload file to S3
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: aws s3 cp --recursive --region ap-northeast-1 dist/ s3://online-code

          # CloudFrontのキャッシュクリア
        - name: Clear cache in CloudFront
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            PATHS: "/*"
            AWS_REGION: 'ap-northeast-1'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}